In [185]:
%load_ext jupyter_black

## NumPy - Numerical Python
**библиотека для эффективных вычислений**

Python -- высокоуровневый, интепретируемый и динамический язык. Списки в нём -- списки указателей на объекты (которые могут иметь любой тип), и при выполнении, например, "векторных операций" (с помощью циклов или list comprehensions) интерпретатор каждый раз проверяет, применим ли тип очередного элемента. 


*То, за счёт чего мы получает лаконичность кода и высокую скорость разработки, вынуждает наши программы работать медленнее.*


В numpy:
1. array должны быть одного типа, поэтому нет дополнительных вычислительных затрат на проверки.
2. Часть операций реализована на C.


Отсюда прирост в производительности на некоторых распространённых задачах -- в сотни раз.


*Неформальное правило: если вы используете numpy и если при этом в вашем коде есть циклы, скорее всего, вы делаете что-то не так.*

In [2]:
import numpy as np

"""
Часто используемые alias'ы:
np ~ numpy
sp ~ scipy
pd ~ pandas
tf ~ tensorflow
plt ~ matplotlib.pyplot
...
"""

# numpy.ndarray -- это элементы ОДНОГО типа (в numpy их много)

array = [1, 222, 33, 5]
nparray = np.array(array, dtype='float')

print(array)
print(type(nparray))
print(nparray)
print(nparray.dtype)

[1, 222, 33, 5]
<class 'numpy.ndarray'>
[  1. 222.  33.   5.]
float64


In [9]:
array = [1, 222, 33, 5.0]
nparray = np.array(array)

print(nparray)
print(nparray.dtype)

[  1. 222.  33.   5.]
float64


In [10]:
class M(object):
    def __init__(self):
        pass

array = [1, 222, 33, "5.0", M()]
nparray = np.array(array)

print(nparray)
print(nparray.dtype)

[1 222 33 '5.0' <__main__.M object at 0x7fe750028890>]
object


In [12]:
nparray.shape

(5,)

In [14]:
np.array([[1,2],[3,4]]).shape

(2, 2)

In [17]:
# arange -- генерация подряд идущих чисел
# reshape -- приведение к нужной размерности
array = np.arange(40).reshape(2, 2, 10)

print(type(array))

print(array)

# размерности
print(array.ndim)

# как нумеруются оси
# строки -- axis=0
# столбцы -- axis=1
print(array.shape)
print(len(array))

print(array.astype(np.float32))

array = array.astype(np.float32)
print(array.dtype)

# также можно задавать многомерные массивы, передав в список списков [списков [списков [...]]

<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]
3
(2, 2, 10)
2
[[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]]]
float32


In [18]:
print(np.arange(40).reshape(2, 2, 10))

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]]


In [19]:
np.arange(40).reshape(2, 2, 10).ndim

3

In [20]:
# Другие методы создания array

# от, до, сколько частей
c = np.linspace(0, 1, 6)
d = np.linspace(0, 1, 6, endpoint=False)
print(c, d)

[0.  0.2 0.4 0.6 0.8 1. ] [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333]


In [24]:
# на вход -- размеры массивов
e = np.zeros((2, 3,2,2,2), dtype=bool)
print(e)

[[[[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]]



 [[[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]]]


In [26]:
ee = np.zeros_like(e)
# np.zeros(e.shape)
print(ee)

[[[[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]]



 [[[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]


  [[[False False]
    [False False]]

   [[False False]
    [False False]]]]]


In [27]:
f = np.ones((2, 2, 3))
print(f)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [28]:
# # на вход -- длина диагонали квадратной матрицы
g = np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
h = np.diag(np.arange(5))
i = np.diag(np.ones(3))
print(h)
print(i)

# # etc

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---

In [31]:
x = np.array([1, 2, 3])
y = np.array([3, 1, 2])
x + y

array([4, 3, 5])

In [32]:
x = np.array([[[1,2,3],
              [4,5,6]],
              [[1,2,3],
              [4,5,6]]])
x.shape

(2, 2, 3)

In [33]:
y = np.array([[1,2,3],
              [4,5,6]])
y.shape

(2, 3)

In [35]:
np.ones(3)

array([1., 1., 1.])

In [37]:
# Случайные числа из разных распределений
import random
# "зерно" для генератора случайных чисел -- для одних и тех же псвдослучайных генераций
np.random.seed(40)

# генерация сэмплов из равномерного распределения
a = np.zeros(4)
for i in range(4):
    a[i] = random.random()
    
    
a = np.random.rand(4)  
print(a)

# гауссовское распределение
b = np.random.randn(50).reshape((2,25))
print(b)

# и есть несколько других полезных на практике, google it

[0.40768703 0.05536604 0.78853488 0.28730518]
[[-1.84440103 -0.46700242  2.29249034  0.48881005  0.71026699  1.05553444
   0.0540731   0.25795342  0.58828165  0.88524424 -1.01700702 -0.13369303
  -0.4381855   0.49344349 -0.19900912 -1.27498361  0.29349415  0.10895031
   0.03172679  1.27263986  1.0714479   0.41581801  1.55067923 -0.31137892
  -1.37923991]
 [ 1.37140879  0.02771165 -0.32039958 -0.84617041 -0.43342892 -1.3370345
   0.20917217 -1.4243213  -0.55347685  0.07479864 -0.50561983  1.05240778
   0.97140041  0.07683154 -0.43500078  0.5529944   0.26671631  0.00898941
   0.64110275 -0.17770716  0.69627761 -1.1887251  -0.33169686  0.03007614
  -1.10791517]]


### Залог эффективных вычислений 
#### воспринимать рекомендации по работе с numpy 
*(ну или заглядывать в исходники, но это для джедаев)*

**Numpy-way strategies**
1. **Использование numpy ufuncs**
2. **Использование numpy aggregate functions**
3. **Slicing, masking, fancy indexing**
4. ***Broadcasting**

#### ufinc
A **universal function** (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. That is, a ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

In [40]:
# Нет ни одного шанса, что мы рассмотрим всё, что есть в numpy.
# Поэтому если есть нужда в решении какой-нибудь задачи линейной алгебры, стоит погуглить,
# наверняка в numpy/scipy есть готовое

# Сейчас учимся, "как делать правильно", а конкретные необходимые вам методы придётся погуглить

x = np.arange(6).reshape((2, 3))
print(x, x.shape)
print(x + 2)
print(x / 2)
print(x * 2)
print(x ** 2)
print(x % 2)

[[0 1 2]
 [3 4 5]] (2, 3)
[[2 3 4]
 [5 6 7]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  4]
 [ 9 16 25]]
[[0 1 0]
 [1 0 1]]


In [41]:
print(x + x)
print(x - x)

[[ 0  2  4]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]


In [42]:
# NOTA BENE!
print(x * x) # element-wise
print(x.dot(x.T)) # multiplication
print(x.T.dot(x)) # multiplication

[[ 0  1  4]
 [ 9 16 25]]
[[ 5 14]
 [14 50]]
[[ 9 12 15]
 [12 17 22]
 [15 22 29]]


In [43]:
# а еще можно вот так
x @ x.T

array([[ 5, 14],
       [14, 50]])

In [44]:
# а давайте проверим
x == x[0]

array([[ True,  True,  True],
       [False, False, False]])

In [45]:
# Сюда же относятся очень эффективные
# np.log
# np.exp
# Можете не писать питоновские лямбды -- не делайте этого

print(x)
print(x[0])
print(np.array([[1, 1, 1], [1, 1, 1]]) * x[0])
x.shape, x[0].shape

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[0 1 2]
 [0 1 2]]


((2, 3), (3,))

In [46]:
np.exp(x)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [47]:
# let's make sure numpy's ufuncs are cool
arr = list(range(0, 60000))
%timeit [v + 5 for v in arr]

arr = np.arange(60000)
%timeit arr + 5

3.24 ms ± 139 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
36.8 μs ± 2.77 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [50]:
# можно обычную функцию перевести вектроризовать!
import math


def my_cos(val):
    if val > 0:
        return math.cos(val)
    else:
        return 123.


my_cos_vectorized = np.vectorize(my_cos)

In [51]:
my_cos_vectorized(arr)

array([123.        ,   0.54030231,  -0.41614684, ...,   0.42077374,
         0.99069857,   0.6497797 ])

#### II. Aggregate functions: берём коллекцию, вычисляем "агрегат"

In [52]:
x = np.arange(60).reshape((10, 6))
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


In [53]:
# среднее по разным измерениям
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

29.5
[27. 28. 29. 30. 31. 32.]
[ 2.5  8.5 14.5 20.5 26.5 32.5 38.5 44.5 50.5 56.5]


In [54]:
# ст. отклонение по разным измерениям
print(np.std(x))
print(np.std(x, axis=0))
print(np.std(x, axis=1))

17.318102282486574
[17.23368794 17.23368794 17.23368794 17.23368794 17.23368794 17.23368794]
[1.70782513 1.70782513 1.70782513 1.70782513 1.70782513 1.70782513
 1.70782513 1.70782513 1.70782513 1.70782513]


In [56]:
# а так что получится?
print(np.std(x, axis=-1))

[1.70782513 1.70782513 1.70782513 1.70782513 1.70782513 1.70782513
 1.70782513 1.70782513 1.70782513 1.70782513]


In [57]:
# let's make sure numpy's aggr funcs are blazing fast
arr = list(range(0, 60000))
%timeit sum(arr)

arr = np.arange(60000)
%timeit np.sum(arr)

# убедительно? :]

619 μs ± 15.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
23.5 μs ± 1.14 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [60]:
# Функции-аггрегации есть на все случаи жизни, и обычно они имеют интуитивные названия:
arr = np.arange(60000).reshape(600, 100)

# угадайте, как найти глобальный максимум 
print(np.max(arr), arr.max())

# А построчный?
print(np.max(arr, axis=1).shape, arr.max(axis=-1).shape)

59999 59999
(600,) (600,)


In [62]:
(np.max(arr, axis=1) == arr.max(axis=-1)).all()

np.True_

#### III. Индексы
Если вы впервые знакомитесь с numpy - обязательно прочитайте [это](https://numpy.org/doc/stable/user/basics.indexing.html)

In [79]:
# III. Продвинутый доступ до элементов -- каждый из них можно применять 
# к ЛЮБОМУ изменению массива

arr = np.arange(120).reshape(12, 10)
print(arr.shape)
# 1. индексы через запятую
print(arr[0])
print(arr[0, 1])
print(arr[0][1])
arr

(12, 10)
[0 1 2 3 4 5 6 7 8 9]
1
1


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [64]:
print(arr[0][1:5:2])

l = list(range(10))
l[:5]

[1 3]


[0, 1, 2, 3, 4]

In [67]:
arr[2:10:3, 1:5:2]

array([[21, 23],
       [51, 53],
       [81, 83]])

In [68]:
# индексация булевыми массивами
arr[0][[True, True, True, True, True, True,False, True, False, False]]

array([0, 1, 2, 3, 4, 5, 7])

In [77]:
arr[:,:, None].shape

(12, 10, 1)

In [70]:
arr.shape

(12, 10)

In [ ]:
# а это что за зверь?
arr[:, np.newaxis, [0, 1], np.newaxis].shape

In [ ]:
np.newaxis is None

In [ ]:
arr[0][arr[0] % 2 == 0]

In [78]:
arr[1:5,[0,-1]]

array([[10, 19],
       [20, 29],
       [30, 39],
       [40, 49]])

In [ ]:
# # 2. слайсинг по любому индексу
print(arr[:2, :])

# # 3. можно передавать список индексов (как лист, так и np.ndarray)
print(arr[[0, 3], :1])
print(arr[np.array([0, 3]), :1])


In [80]:
arr[(arr%4) == 3]

array([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
        55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
       107, 111, 115, 119])

In [107]:
# # 4. хитрый отбор элементов -- masking
x = np.random.randn(100)

# элементы больше среднего
print(x[x > x.mean()])

[0.86875688 0.25814429 0.98601993 0.56792521 1.07434477 0.93008559
 1.11634409 1.52204941 0.11594107 0.71244864 1.25016352 1.7980126
 2.13568999 0.6970301  1.3388364  0.19627482 0.91150536 1.15590495
 0.98690552 0.84583745 0.56835203 0.96406943 0.4600068  0.85452543
 0.32495387 0.27333806 0.49038683 0.75004037 1.10594204 0.60509526
 2.0642895  0.17919391 0.70199476 0.91630957 0.22462536 1.24142861
 0.46203309 0.70843789 0.29426351 0.70183516 0.45365311 1.5421307
 0.6829811  1.22533109 1.22407522 3.00373544 1.47102214 0.64574329
 0.65081061]


In [130]:
# всё, что выпадает за три сигмы

print(x[(x > x.mean() + 3 * x.std()) | (x < x.mean() - 3 * x.std())].shape)

# %timeit ...

(1,)


In [134]:
x = np.arange(60).reshape(2, 3, 5, 2)

x[..., [0,1],:].shape

(2, 3, 2, 2)

In [5]:
# mn = np.mean(x)
# std = 3 * np.std(x)
# mnstdr = mn + std
# mnstdl = mn - std

# %timeit filter(lambda x: x > mnstdr or x < mnstdl, x)


# У маскинга свой небольшой язык
# Например,
# not = ~
# and = &
# or = |
# >, <, >=, <=

#### IV* Broadcasting

In [138]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [146]:
x = x[None, :]
x

array([[[1, 2, 3]]])

In [149]:
y = np.array([[1], [4]])

y

array([[1],
       [4]])

In [150]:
x + y

array([[[2, 3, 4],
        [5, 6, 7]]])

In [151]:
# https://numpy.org/doc/stable/user/basics.broadcasting.html - посмотрите хотя-бы картинки, будет гораздо понятнее
# часто возникает необходимость делать операции с массивами формально неподходящего размера:
np.arange(10) + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [152]:
# а так -- можно?
np.arange(10) + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (10,) (2,) 

In [155]:
x = np.arange(10).reshape(5, 2)
y = np.array([1, 2])
(x + y).reshape(10)

array([ 1,  3,  3,  5,  5,  7,  7,  9,  9, 11])

In [156]:
# А это почему так получилось?
x = np.arange(10).reshape(2, 5)
y = np.array([[1], [2]])
(x + y).reshape(10)

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

---

In [161]:
# Пусть у нас есть точка x и массив точек X. Как мне найти близжайшую к X точку в массиве?

x = np.array([111.0, 188.0])
X = np.array([[132.0, 193.0],[102.0, 203.0], [45.0, 155.0], [57.0, 173.0]])

X - x



array([[ 21.,   5.],
       [ -9.,  15.],
       [-66., -33.],
       [-54., -15.]])

In [162]:
((X - x) ** 2).sum(axis=1).argmin()

np.int64(1)

Более строго, правила такие:

**Rule 1**: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Rule 2**: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

**Rule 3**: If in any dimension the sizes disagree and neither is equal to 1, an error is raised:

# Упражнения

In [163]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [167]:
# Find indices of non-zero elements from given array x

x = np.array([1, 2,  0, 6, 0, 1]) # [2, 4]

np.arange(len(x))[x != 0]

array([0, 1, 3, 5])

In [186]:
# How to add a border (filled with 0's) around an existing array?
x = np.arange(12).reshape(3, 4)
np.hstack([x, np.zeros_like(x[:, :1])])

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  0],
       [ 8,  9, 10, 11,  0]])

In [178]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
np.zeros(x.shape[0])

array([0., 0., 0.])

In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place

In [ ]:
# Create random vector of size 10 and replace the maximum value by 0

In [ ]:
# How to find common values between two arrays?

In [ ]:
# Given a two dimensional array, how to extract unique rows?

In [ ]:
# How to get the n largest values of an array

In [ ]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?

In [ ]:
# Consider two arrays A and B of shape (8,3) and (2,2). 
# How to find rows of A that contain elements of each 
# row of B regardless of the order of the elements in B?

In [183]:
# Considering a 10x3 matrix, extract rows with unequal values

### Задача 1: Попарные углы (1 балл)

Даны набор векторов. Без использования циклов в Python найдите номера двух различных векторов, угол между которыми - минимален. Максимум 3 строки, соответсвующие форматированию jupyter_black.

In [28]:
# 10 векторов в R^4
x = np.array(
    [
        [-1.05247805, 0.0813231, 0.94708268, -0.53371674],
        [0.01359646, -1.43838044, 1.01326978, -0.38062482],
        [0.30563645, 1.18997822, 0.48149476, 0.83524308],
        [1.22609704, 1.72169283, -0.21137761, -1.21598295],
        [0.6397264, -1.24751009, 0.03137696, 0.55576899],
        [1.55630085, 1.2840827, -0.52525765, 2.4523538],
        [-1.70632707, 0.45006017, -1.04214031, -1.47674443],
        [-0.51870141, -0.01755243, 1.95102122, 0.36809772],
        [-0.97629927, 0.35430853, -0.63895086, -0.2467184],
        [-0.51120513, -0.33014789, -1.45017724, -0.02398285],
    ]
)

y = np.dot(x, x.T) / np.matmul(np.linalg.norm(x, axis=1).reshape(10, 1), np.linalg.norm(x, axis=1).reshape(1, 10)) - np.eye(10)
i, j = (y.argmax() // y.shape[0], y.argmax() % y.shape[0])
assert (i, j) == (6, 8) or (i, j) == (8, 6), "Wrong Answer"

### Задача 2: Cвертка (1 балл)
Реализуйте двумерную свертку при помощи numpy без использования циклов в python. 
Максимум 4 строки,  соответсвующие форматированию jupyter_black.

![](https://upload.wikimedia.org/wikipedia/commons/1/19/2D_Convolution_Animation.gif)



In [4]:
x = np.arange(64).reshape((8, 8))
kernel = np.array([[1, -1, 2], [3, -2, 1], [0, 0, 1]])
print(x)

# XV, YV = np.meshgrid(np.arange(0, (x.shape[0]-2)), np.arange(0, (x.shape[0]-2)))
# indexes = np.array([np.column_stack((XV.ravel(), YV.ravel())), np.column_stack((XV.ravel(), YV.ravel())) + [2, 2]])
# print(x[indexes[0,:,:], indexes[1,:,:]])

x = np.array([np.sum((x[i:i+3, j:j+3])*kernel) for i in range(x.shape[0]-2) for j in range(x.shape[1]-2)]).reshape(x.shape[0]-2,x.shape[1]-2)
print(x)

ans = np.array(
    [
        [37, 42, 47, 52, 57, 62],
        [77, 82, 87, 92, 97, 102],
        [117, 122, 127, 132, 137, 142],
        [157, 162, 167, 172, 177, 182],
        [197, 202, 207, 212, 217, 222],
        [237, 242, 247, 252, 257, 262],
    ]
)
assert (x == ans).all(), "Wrong answer"

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[[ 37  42  47  52  57  62]
 [ 77  82  87  92  97 102]
 [117 122 127 132 137 142]
 [157 162 167 172 177 182]
 [197 202 207 212 217 222]
 [237 242 247 252 257 262]]


----

This notebook was adapted from Anton Alekseev's practical lessons on MCS SPBU, [tutorial from CS231N at Stanford University](https://cs231n.github.io/python-numpy-tutorial/), and [NumPy documentation](https://numpy.org/doc/stable/index.html).