In [1]:
import numpy as np

In [2]:
np.random.seed(100)

# Create synthetic dataset for training and testing
means0, covs0 = [1, -1], [[7, 3], [3, 7]]
x0, y0 = np.random.multivariate_normal(means0, covs0, 190).T

means1, covs1 = [0, -4], [[0.1, 0.0], [0.0, 25]]
x1, y1 = np.random.multivariate_normal(means1, covs1, 100).T

In [3]:
x0.shape

(190,)

In [4]:
# Convert data to the appropriate format
data0, labels0 = np.vstack([x0, y0]).T, np.zeros(len(x0))
data1, labels1 = np.vstack([x1, y1]).T, np.ones(len(x1))

data = np.vstack([data0, data1])
labels = np.hstack([labels0, labels1])
total_size = data.shape[0]
print("Dataset shape:", data.shape, labels.shape)

# Split dataset into 70% train and 30% test
train_size = int(total_size * 0.7)
indices = np.random.permutation(total_size)
X_train, y_train = data[indices][:train_size], labels[indices][:train_size]
X_test, y_test = data[indices][train_size:], labels[indices][train_size:]
print("Train/test shapes:", X_train.shape, X_test.shape)

Dataset shape: (290, 2) (290,)
Train/test shapes: (203, 2) (87, 2)


In [6]:
A = np.zeros([87,10])
A[:, 0] = np.ones([87,])
A1 = np.repeat(A, 203).reshape([87, 10, 203])
A1.shape

(87, 10, 203)

In [7]:
B = np.zeros([203,10])
B[:,0] = np.ones([203,])
B1 = np.repeat(B, 87).reshape([203, 10, 87]).T
B1.shape

(87, 10, 203)

In [8]:
D = np.linalg.norm(np.repeat(X_test, X_train.shape[0]).reshape([X_test.shape[0], X_test.shape[1], X_train.shape[0]]) - np.repeat(X_train, X_test.shape[0]).reshape([X_train.shape[0], X_test.shape[1], X_test.shape[0]]).T, axis=1, )

In [9]:
D.shape

(87, 203)

In [10]:
d = np.stack([D, np.repeat(y_train, 87).reshape([203,87]).T], axis=2)
d.shape

(87, 203, 2)

In [11]:
y_train

array([0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.])

In [39]:
classes = np.repeat(y_train, 87).reshape([203,87]).T

sort_ids = np.argsort(D, axis=1)
d_sorted = np.dstack([np.take_along_axis(D, sort_ids, axis=1), np.take_along_axis(classes, sort_ids, axis=1)])

d_sorted[:3,:7,0]

array([[0.12324413, 0.28885728, 0.47394092, 0.64423232, 0.74208156,
        1.12386719, 1.52022858],
       [0.54217517, 0.85485105, 0.9787039 , 1.05287902, 1.32644576,
        1.32729004, 1.43318384],
       [0.25487624, 0.37786514, 0.42385722, 0.58474002, 0.63621091,
        0.67734804, 0.81796678]])

In [38]:
d_sorted[:3,:7,1]

array([[1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 1., 1., 1.]])

In [44]:
arr1 = np.count_nonzero(d_sorted[:3,:7,1] == 0, axis=1)
arr1

array([0, 7, 1])

In [45]:
arr2 = np.count_nonzero(d_sorted[:3,:7,1] == 1, axis=1)
arr2

array([7, 0, 6])

In [48]:
np.array(arr1 < arr2, dtype="float64")

array([1., 0., 1.])